apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: piuxrmo9k-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:0fcacbaa93e4d010b348f97cb51f9d6f2c32d8fa@sha256:51d7bf3169265fb13948f558fe12d61990e477eb6ce70cf3b48196ba84b11a4a
          name: container-image
